name = "miara"
compatibility_date = "2024-1-10"
send_metrics = false
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "miara"
database_id = "bd807ada-9eaa-43ab-8796-b2504c4cc907"
preview_database_id = "miara"
